ete_url: http://etengine.local.energytransitionmodel.com:3000

identity:
  issuer: http://myetm.local.energytransitionmodel.com:3002
  client_id: etm-local-etmodel-client
  client_secret: etm-local-etmodel-secret-000000000000
  client_uri: http://etmodel.local.energytransitionmodel.com:3001

collections_url: http://collections.local.energytransitionmodel.com:3005
